# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.8"

# Versão do Ubuntu
dist: focal
os: linux

addons:
  sonarcloud:
    organization: lfukama
    token: ${SONAR_TOKEN}

before_install:
  - openssl aes-256-cbc -K $encrypted_d2f50c5f0871_key -iv $encrypted_d2f50c5f0871_iv -in gcpterraformkey.json.enc -out ../gcpterraformkey.json -d

jobs:
  include:
    - stage: Build & Tests
      name: "Unit Test, Quality & Security"

      # Instalação de Módulos que são necessários para a Aplicação.
      install:
        - pip install flask pytest flask-wtf covarage

      # Defini o script de Teste que deve rodar toda vez que o código for alterado.
      script:
        - coverage report app.py || travis_terminate 1;
        - coverage xml app.py || travis_terminate 1;
        - sonar-scanner || travis_terminate 1;
 
    - stage: Stage Deploy
      name: Heroku Deploy
      script: skip

      # Definir o Deploy no Heroku
      deploy:
        provider: heroku
        strategy: api
        api_key: $HEROKU_API_KEY
        edge: true
        app: devopslab1-lfukama
        on:
          branch: main
 
    - stage: Stage Test
      name: GET URL Stage
      script:
        - curl https://devopslab1-lfukama.herokuapp.com/ | grep Hello World || travis_terminate 1;

    - stage: Production Deploy
      name: Google Api Engine
      script: skip

      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../gcpterraformkey.json
        project: labdevopscloud-lfukama01
        on:
          branch: main

    - stage: Production Test
      name: GET URL Production
      script:
        - curl https://devopslab1-lfukama.uc.r.appspot.com/ | grep Hello World || travis_terminate 1;
